version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
    open-pull-requests-limit: 5
    labels:
      - "npm dependencies"
      - "dependabot"
    versioning-strategy: auto
    groups:
      npm-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      npm-major:
        update-types:
          - "major"
    commit-message:
      prefix: "npm"
      prefix-development: "dev"
      include: "scope"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
    open-pull-requests-limit: 5
    labels:
      - "docker dependencies"
      - "dependabot"
    groups:
      docker-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      docker-major:
        update-types:
          - "major"
    cooldown:
      default-days: 7

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
    open-pull-requests-limit: 5
    labels:
      - "github actions"
      - "dependabot"
    groups:
      actions-minor-and-patch:
        update-types:
          - "minor"
          - "patch"
      actions-major:
        update-types:
          - "major"
    cooldown:
      default-days: 7